# Divergence from upstream: disable fast dead node detection for layer 2. We use BGP and therefore
# have no use for this functionality. This way we also don't have to deal with generating
# memberlist secrets.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: metallb
    component: speaker
  name: speaker
  namespace: metallb-system
spec:
  selector:
    matchLabels:
      app: metallb
      component: speaker
  template:
    metadata:
      annotations:
        prometheus.io/port: '7472'
        prometheus.io/scrape: 'true'
      labels:
        app: metallb
        component: speaker
    spec:
      containers:
      - args:
        - --metrics-port=7472
        - --status-port=7473
        - --config=config
        env:
        - name: METALLB_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: METALLB_METRICS_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        #- name: METALLB_ML_BIND_ADDR
        #  valueFrom:
        #    fieldRef:
        #      fieldPath: status.podIP
        # needed when another software is also using memberlist / port 7946
        #- name: METALLB_ML_BIND_PORT
        #  value: "7946"
        #- name: METALLB_ML_LABELS
        #  value: "app=metallb,component=speaker"
        #- name: METALLB_ML_NAMESPACE
        #  valueFrom:
        #    fieldRef:
        #      fieldPath: metadata.namespace
        #- name: METALLB_ML_SECRET_KEY
        #  valueFrom:
        #    secretKeyRef:
        #      name: memberlist
        #      key: secretkey
        image: quay.io/kinvolk/metallb-speaker:{{ .Chart.AppVersion }}
        imagePullPolicy: Always
        name: speaker
        ports:
        - containerPort: 7472
          name: monitoring
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN
            drop:
            - ALL
          readOnlyRootFilesystem: true
      hostNetwork: true
      {{- if .Values.speaker.nodeSelector }}
      # XXX: Lokomotive specific change.
      nodeSelector:
{{ toYaml .Values.speaker.nodeSelector | indent 8 }}
      {{- end }}
      serviceAccountName: speaker
      terminationGracePeriodSeconds: 2
      {{- if .Values.speaker.tolerations }}
      # XXX: Lokomotive specific change.
      tolerations:
{{ toYaml .Values.speaker.tolerations | indent 6 }}
      {{- end }}
