apiVersion: v1
appVersion: v0.8.8
description: |
  This chart installs a [node-problem-detector](https://github.com/kubernetes/node-problem-detector) daemonset. This tool aims to make various node problems visible to the upstream layers in cluster management stack. It is a daemon which runs on each node, detects node problems and reports them to apiserver.
engine: gotpl
home: https://github.com/kubernetes/node-problem-detector
icon: https://github.com/kubernetes/kubernetes/raw/master/logo/logo.png
keywords:
- node
- problem
- detector
- monitoring
maintainers:
- email: no-reply@deliveryhero.com
  name: max-rocket-internet
name: node-problem-detector
sources:
- https://github.com/kubernetes/node-problem-detector
- https://kubernetes.io/docs/concepts/architecture/nodes/#condition
version: 2.0.2
