calico:
  networkMTU: 1500
  image: quay.io/kinvolk/calico-node:v3.19.1
  cniImage: quay.io/kinvolk/calico-cni:v3.19.1
  controllersImage: quay.io/kinvolk/calico-kube-controllers:v3.19.1
  flexvolDriverImage: quay.io/kinvolk/calico-pod2daemon-flexvol:v3.19.1
  enableReporting: false
  networkIpAutodetectionMethod: first-found
  ipipEnabled: true
  vxlanEnabled: false
  # Add something like `- --bird-ready` with correct indentation
  ipipReadiness: ""
  podCIDR: 10.2.0.0/16
  networkEncapsulation: "ipipMode: Always"
  blockedMetadataCIDRs: []
  # Lokomotive specific change.
  # failsafeInboundHostPorts:
  encryptPodTraffic: false
