apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: flatcar-linux-update-agent
  namespace: reboot-coordinator
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: flatcar-linux-update-agent
    spec:
      serviceAccountName: flatcar-linux-update-operator-sa
      containers:
      - name: update-agent
        image: quay.io/kinvolk/flatcar-linux-update-operator:v0.7.0
        command:
        - "/bin/update-agent"
        volumeMounts:
          - mountPath: /var/run/dbus
            name: var-run-dbus
            readOnly: false
          - mountPath: /etc/flatcar
            name: etc-flatcar
            readOnly: true
          - mountPath: /usr/share/flatcar
            name: usr-share-flatcar
            readOnly: true
          - mountPath: /etc/os-release
            name: etc-os-release
            readOnly: true
        env:
        # read by update-agent as the node name to manage reboots for
        - name: UPDATE_AGENT_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      volumes:
      - name: var-run-dbus
        hostPath:
          path: /var/run/dbus
      - name: etc-flatcar
        hostPath:
          path: /etc/flatcar
      - name: usr-share-flatcar
        hostPath:
          path: /usr/share/flatcar
      - name: etc-os-release
        hostPath:
          path: /etc/os-release
