apiVersion: v1
appVersion: 0.8.1
description: A Helm chart for AWS EBS CSI Driver
home: https://github.com/kubernetes-sigs/aws-ebs-csi-driver
keywords:
- aws
- ebs
- csi
kubeVersion: '>=1.14.0-0'
maintainers:
- email: chengpan@amazon.com
  name: leakingtapan
- name: krmichel
  url: https://github.com/krmichel
name: aws-ebs-csi-driver
sources:
- https://github.com/kubernetes-sigs/aws-ebs-csi-driver
version: 0.8.2
