apiVersion: v2
appVersion: 2.10.0
dependencies:
- condition: openebsLocalpv.enabled
  name: localpv-provisioner
  repository: https://openebs.github.io/dynamic-localpv-provisioner
  version: 2.10.0
description: Jiva-Operator helm chart for Kubernetes
home: http://www.openebs.io/
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/openebs/icon/color/openebs-icon-color.png
keywords:
- cloud-native-storage
- block-storage
- iSCSI
- storage
- jiva
- jiva-operator
maintainers:
- email: prateek.pandey@mayadata.io
  name: prateekpandey14
- email: shubham.bajpai@mayadata.io
  name: shubham14bajpai
name: jiva
sources:
- https://github.com/openebs/jiva-operator
type: application
version: 2.10.1
