calico:
  networkMTU: ${network_mtu}
  image: ${calico_image}
  cniImage: ${calico_cni_image}
  enableReporting: ${enable_reporting}
  networkIpAutodetectionMethod: ${network_ip_autodetection_method}
  ipipEnabled: ${ipip_enabled}
  vxlanEnabled: ${vxlan_enabled}
  ipipReadiness: "${ipip_readiness}"
  podCIDR: ${pod_cidr}
  networkEncapsulation: "${network_encapsulation}"
