# Default values for openebs-lvmlocalpv.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
release:
  version: "0.6.0"

imagePullSecrets:
# - name: "image-pull-secret"

# enable storage capacity tracking feature
# Ref: https://kubernetes:io/docs/concepts/storage/storage-capacity
storageCapacity: true

rbac:
  # rbac.pspEnabled: `true` if PodSecurityPolicy resources should be created
  pspEnabled: false

# lvmNode contains the configurables for
# the lvm node daemonset
lvmNode:
  componentName: openebs-lvm-node
  driverRegistrar:
    name: "csi-node-driver-registrar"
    image:
      # Make sure that registry name end with a '/'.
      # For example : k8s.gcr.io/ is a correct value here and quay.io is incorrect
      registry: k8s.gcr.io/
      repository: sig-storage/csi-node-driver-registrar
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: v2.1.0
  updateStrategy:
    type: RollingUpdate
  annotations: {}
  podAnnotations: {}
  # This can be configured to run on various different k8s ditributions like
  # microk8s where kubelet dir is different
  kubeletDir: "/var/lib/kubelet/"
  resources: {}
#    limits:
#      cpu: 10m
#      memory: 32Mi
#    requests:
#      cpu: 10m
#      memory: 32Mi
  ## Labels to be added to openebs-lvm node pods
  podLabels:
    name: openebs-lvm-node
  nodeSelector: {}
  tolerations: []
  securityContext: {}
  labels: {}

# lvmController contains the configurables for
# the lvm controller statefulset
lvmController:
  componentName: openebs-lvm-controller
  replicas: 1
  serviceName: openebs-lvm
  resizer:
    name: "csi-resizer"
    image:
      # Make sure that registry name end with a '/'.
      # For example : k8s.gcr.io/ is a correct value here and quay.io is incorrect
      registry: k8s.gcr.io/
      repository: sig-storage/csi-resizer
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: v1.1.0
  snapshotter:
    name: "csi-snapshotter"
    image:
      # Make sure that registry name end with a '/'.
      # For example : k8s.gcr.io/ is a correct value here and quay.io is incorrect
      registry: k8s.gcr.io/
      repository: sig-storage/csi-snapshotter
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: v4.0.0
  snapshotController:
    name: "snapshot-controller"
    image:
      # Make sure that registry name end with a '/'.
      # For example : k8s.gcr.io/ is a correct value here and quay.io is incorrect
      registry: k8s.gcr.io/
      repository: sig-storage/snapshot-controller
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: v4.0.0
  provisioner:
    name: "csi-provisioner"
    image:
      # Make sure that registry name end with a '/'.
      # For example : k8s.gcr.io/ is a correct value here and quay.io is incorrect
      registry: k8s.gcr.io/
      repository: sig-storage/csi-provisioner
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: v2.1.0
  updateStrategy:
    type: RollingUpdate
  annotations: {}
  podAnnotations: {}
  resources: {}
#    limits:
#      cpu: 10m
#      memory: 32Mi
#    requests:
#      cpu: 10m
#      memory: 32Mi
  ## Labels to be added to openebs-lvm controller pods
  podLabels:
    name: openebs-lvm-controller
  nodeSelector: {}
  tolerations: []
  securityContext: {}

# lvmPlugin is the common csi container used by the
# controller statefulset and node daemonset
lvmPlugin:
  name: "openebs-lvm-plugin"
  image:
    # Make sure that registry name end with a '/'.
    # For example : k8s.gcr.io/ is a correct value here and quay.io is incorrect
    registry:
    repository: openebs/lvm-driver
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 0.6.0
  ioLimits:
    enabled: false
    containerRuntime: containerd
    readIopsPerGB: ""
    writeIopsPerGB: ""

role: openebs-lvm

crd:
  enableInstall: true

serviceAccount:
  lvmController:
    # Specifies whether a service account should be created
    create: true
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: openebs-lvm-controller-sa
  lvmNode:
    # Specifies whether a service account should be created
    create: true
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: openebs-lvm-node-sa

analytics:
  enabled: true
