controllerManager:
  serviceAccountKey:
  caCert:
  caKey:
  image: k8s.gcr.io/kube-controller-manager:v1.18.4
  cloudProvider:
  serviceCIDR: 10.0.0.0/24
  podCIDR: 10.2.0.0/16
  controlPlaneReplicas: 1
  trustedCertsDir: /usr/share/ca-certificates
kubeProxy:
  image: k8s.gcr.io/kube-proxy:v1.18.4
  podCIDR: 10.2.0.0/16
  trustedCertsDir: /usr/share/ca-certificates
kubeScheduler:
  image: k8s.gcr.io/kube-scheduler:v1.18.4
  controlPlaneReplicas: 1
kubeConfigInCluster:
  server:
coredns:
  clusterDomainSuffix: cluster.local
  controlPlaneReplicas: 1
  image: coredns/coredns:coredns-amd64
  clusterIP: 10.0.0.10
etcd:
  endpoints: []
