apiVersion: v2
appVersion: 1.8.0
description: CSI Driver for dynamic provisioning of ZFS Persistent Local Volumes.
home: http://www.openebs.io/
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/openebs/icon/color/openebs-icon-color.png
keywords:
- cloud-native-storage
- block-storage
- filesystem
- ZFS
- Local Persistent Volumes
- storage
maintainers:
- email: michaelfornaro@gmail.com
  name: xUnholy
- email: prateek.pandey@mayadata.io
  name: prateekpandey14
- email: pawan@mayadata.io
  name: pawanpraka1
name: zfs-localpv
sources:
- https://github.com/openebs/zfs-localpv
version: 1.8.0
