{{- if .Values.clusterRole.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: '{{ .Values.clusterRole.name }}'
  labels:
    {{- include "cloud-provider-equinix-metal.labels" . | nindent 4 }}
  {{- with .Values.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ .Values.clusterRole.name }}'
subjects:
  - kind: ServiceAccount
    name: {{ include "cloud-provider-equinix-metal.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}